### ISSUE TITLE
 There are no commands defined in the "backup" namespace.

### ISSUE THREAD

**Issue by savosik** [BlackbitDigitalCommerce/pimcore-backup#1]
When I run   "php /var/www/html/bin/console backup:backup"  I have this message " There are no commands defined in the "backup" namespace."

**Comment by BlackbitDevs** [comment]
Have you enabled and installed the bundle?
Please run `php /var/www/html/bin/console pimcore:bundle:list` and post the output here

**Comment by BlackbitDevs** [comment]
I close this issue for now. If you still do not see the commands after installing and enabling the bundle, just comment here again.
