### ISSUE TITLE
Pimcore 11 compatiblity

### ISSUE THREAD

**Issue by matthiashamacher** [BlackbitDigitalCommerce/pimcore-backup#10]
Are there any plans regarding Pimcore 11 compatibility?

**Comment by BlackbitDevs** [comment]
In general yes but there are other plugins which we currently focus more to make compatible with Pimcore 11. But of course we appreciate pull requests...

**Comment by matthiashamacher** [comment]
Just created a PR #11 for basic compatibility. Haven't tested all but backup and restore command seem to work now
