### ISSUE TITLE
Incompatible with Symfony TreeBuilder

### ISSUE THREAD

**Issue by gilsys** [BlackbitDigitalCommerce/pimcore-backup#2]
php console pimcore:bundle:list
ArgumentCountError {#2001
  #message: "Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in Z:\data\www\pimacmarcax\pimacmarcax\vendor\blackbit_digital_commerce\pimcore-backup\DependencyInjection\Configuration.php on line 29 and at least 1 expected"
  #code: 0
  #file: "Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\config\Definition\Builder\TreeBuilder.php"
  #line: 26
  trace: {
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\config\Definition\Builder\TreeBuilder.php:26 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\blackbit_digital_commerce\pimcore-backup\DependencyInjection\Configuration.php:29 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\config\Definition\Processor.php:50 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\dependency-injection\Extension\Extension.php:111 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\blackbit_digital_commerce\pimcore-backup\DependencyInjection\BackupExtension.php:32 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\dependency-injection\Compiler\MergeExtensionConfigurationPass.php:76 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\http-kernel\DependencyInjection\MergeExtensionConfigurationPass.php:39 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\dependency-injection\Compiler\Compiler.php:91 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\dependency-injection\ContainerBuilder.php:744 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\http-kernel\Kernel.php:545 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\pimcore\pimcore\lib\Kernel.php:225 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\http-kernel\Kernel.php:786 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\http-kernel\Kernel.php:125 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\pimcore\pimcore\lib\Kernel.php:204 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\pimcore\pimcore\lib\Bootstrap.php:256 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\vendor\pimcore\pimcore\lib\Bootstrap.php:60 { …}
    Z:\data\www\pimacmarcax\pimacmarcax\bin\console:46 {
      › /** @var \Pimcore\Kernel $kernel */
      › $kernel = \Pimcore\Bootstrap::startupCli();
      › $application = new \Pimcore\Console\Application($kernel);
    }
  }
}

**Comment by BlackbitDevs** [comment]
Which symfony version do you use?
Have a look at `composer info symfony/symfony` and there what is under `version`

**Comment by gilsys** [comment]
I'm testing with a fresh pimcore x installation, it does not have symfony/symfony.
The error is throwed by symfony/config, v5.3.4

name     : symfony/config
descrip. : Helps you find, load, combine, autofill and validate configuration values of any kind
keywords :
versions : * v5.3.4
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://symfony.com
source   : [git] https://github.com/symfony/config.git 4268f3059c904c61636275182707f81645517a37
dist     : [zip] https://api.github.com/repos/symfony/config/zipball/4268f3059c904c61636275182707f81645517a37 4268f3059c904c61636275182707f81645517a37
path     : Z:\data\www\pimacmarcax\pimacmarcax\vendor\symfony\config
names    : symfony/config

support
source : https://github.com/symfony/config/tree/v5.3.4

autoload
psr-4
Symfony\Component\Config\ => .
exclude-from-classmap

requires
php >=7.2.5
symfony/deprecation-contracts ^2.1
symfony/filesystem ^4.4|^5.0
symfony/polyfill-ctype ~1.8
symfony/polyfill-php80 ^1.16
symfony/polyfill-php81 ^1.22

requires (dev)
symfony/event-dispatcher ^4.4|^5.0
symfony/finder ^4.4|^5.0
symfony/messenger ^4.4|^5.0
symfony/service-contracts ^1.1|^2
symfony/yaml ^4.4|^5.0

suggests
symfony/yaml To use the yaml reference dumper

conflicts
symfony/finder <4.4

**Comment by BlackbitDevs** [comment]
Is fixed in the just released version 1.2.3
Implemented it the same way as in https://github.com/BlackbitDigitalCommerce/pimcore-ldap-bundle/pull/17
