### ISSUE TITLE
Error composer require

### ISSUE THREAD

**Issue by gilsys** [BlackbitDigitalCommerce/pimcore-backup#3]
> Pimcore\Composer::installAssets

Fatal error: Uncaught Error: Class "blackbit\BackupBundle\DependencyInjection\Kernel" not found in /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/Configuration.php:29
Stack trace:
#0 /var/www/html/vendor/symfony/config/Definition/Processor.php(50): blackbit\BackupBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#1 /var/www/html/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(blackbit\BackupBundle\DependencyInjection\Configuration), Array)
#2 /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/BackupExtension.php(32): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(blackbit\BackupBundle\DependencyInjection\Configuration), Array)
#3 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): blackbit\BackupBundle\DependencyInjection\BackupExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(744): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /var/www/html/vendor/symfony/http-kernel/Kernel.php(545): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(225): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(786): Pimcore\Kernel->initializeContainer()
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(125): Symfony\Component\HttpKernel\Kernel->preBoot()
#11 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(204): Symfony\Component\HttpKernel\Kernel->boot()
#12 /var/www/html/vendor/pimcore/pimcore/lib/Bootstrap.php(256): Pimcore\Kernel->boot()
#13 /var/www/html/vendor/pimcore/pimcore/lib/Bootstrap.php(60): Pimcore\Bootstrap::kernel()
#14 /var/www/html/bin/console(46): Pimcore\Bootstrap::startupCli()
#15 {main}
  thrown in /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/Configuration.php on line 29
Script Pimcore\Composer::installAssets handling the pimcore-scripts event terminated with an exception

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

  [RuntimeException]
  An error occurred when executing the "/usr/local/bin/php bin/console --ansi assets:install --symlink --relative public" command:

  Exit code: 255

  Fatal error: Uncaught Error: Class "blackbit\BackupBundle\DependencyInjection\Kernel" not found in /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/Configuration.php:29
  Stack trace:
  #0 /var/www/html/vendor/symfony/config/Definition/Processor.php(50): blackbit\BackupBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
  #1 /var/www/html/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(blackbit\BackupBundle\DependencyInjection\Configuration), Array)
  #2 /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/BackupExtension.php(32): Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration(Object(blackbit\BackupBundle\DependencyInjection\Configuration), Array)
  #3 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): blackbit\BackupBundle\DependencyInjection\BackupExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
  #4 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #5 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(91): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #6 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(744): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
  #7 /var/www/html/vendor/symfony/http-kernel/Kernel.php(545): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
  #8 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(225): Symfony\Component\HttpKernel\Kernel->initializeContainer()
  #9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(786): Pimcore\Kernel->initializeContainer()
  #10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(125): Symfony\Component\HttpKernel\Kernel->preBoot()
  #11 /var/www/html/vendor/pimcore/pimcore/lib/Kernel.php(204): Symfony\Component\HttpKernel\Kernel->boot()
  #12 /var/www/html/vendor/pimcore/pimcore/lib/Bootstrap.php(256): Pimcore\Kernel->boot()
  #13 /var/www/html/vendor/pimcore/pimcore/lib/Bootstrap.php(60): Pimcore\Bootstrap::kernel()
  #14 /var/www/html/bin/console(46): Pimcore\Bootstrap::startupCli()
  #15 {main}
    thrown in /var/www/html/vendor/blackbit_digital_commerce/pimcore-backup/DependencyInjection/Configuration.php on line 29

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

ERROR: 1

**Comment by BlackbitDevs** [comment]
Fixed in 1.2.4 - thanks for your report.
