### ISSUE TITLE
Error on backup:sync from local Docker

### ISSUE THREAD

**Issue by jc-fwg** [BlackbitDigitalCommerce/pimcore-backup#5]
Trying to bring backup:sync to work. Using

`./bin/console backup:sync user@host /path/to/application`

bring following error:

`Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher::dispatch(): Argument #1 ($event) must be of type object, string given, called in /Users/xxx/Projects/xxx/xxx-pimcorex/application/vendor/blackbit_digital_commerc  
  e/pimcore-backup/Command/SyncCommand.php on line 143`

**Comment by jc-fwg** [comment]
Sorry forgot specs:
Docker on MacOS, PHP 8.1

**Comment by BlackbitDevs** [comment]
Is fixed. Could you try with `dev-master`, please?
Please report if it works or not, so that I can release a new version.

**Comment by BlackbitDevs** [comment]
@jc-fwg Do you have any feedback? Does it work now?

**Comment by jc-fwg** [comment]
@BlackbitNeueMedien seems to work. error does not appear anymore. thx for the fast fix!
got another issue now. but will open another issue if I won't find a solution on it :)

**Comment by BlackbitDevs** [comment]
Thx for your feedback.
Released version 1.2.6
