### ISSUE TITLE
Issue with --set-gtid-purged=OFF when using MariaDB 10.3 

### ISSUE THREAD

**Issue by dgonzalez360** [BlackbitDigitalCommerce/pimcore-backup#6]
I'm having an issue when trying to backup my installation, I get the following message:

mysqldump: unknown variable 'set-gtid-purged=OFF'

Pimcore: 10.4.3
MariaDB: 10.3.34-MariaDB

**Comment by dgonzalez360** [comment]
#7 Should solve this issue

**Comment by BlackbitDevs** [comment]
#7 resolved this.
